# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from py.User import sign_in, register, LoginException, save_pickled


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(320, 180)
        MainWindow.setMouseTracking(False)
        # MainWindow.setStyleSheet("background-color: rgb(198, 140, 83)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 111))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.label_login = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_login.setFont(font)
        self.horizontalLayout.addWidget(self.label_login)
        spacerItem = QtWidgets.QSpacerItem(46, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.entry_login = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.entry_login.setFont(font)
        # self.entry_login.setStyleSheet("background-color: rgb(217, 179, 140)")
        self.horizontalLayout.addWidget(self.entry_login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_password.setFont(font)
        self.horizontalLayout_2.addWidget(self.label_password)
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.entry_password = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.entry_password.setFont(font)
        # self.entry_password.setStyleSheet("background-color: rgb(217, 179, 140)")
        self.horizontalLayout_2.addWidget(self.entry_password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 130, 191, 26))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.button_sign_in = QtWidgets.QPushButton(self.layoutWidget1, clicked=self.try_sign_in)
        # self.button_log_out.setStyleSheet("background-color: rgb(217, 179, 140)")
        self.horizontalLayout_3.addWidget(self.button_sign_in)
        self.button_new_account = QtWidgets.QPushButton(self.layoutWidget1, clicked=self.try_register)
        # self.button_new_account.setStyleSheet("background-color: rgb(217, 179, 140);")
        self.horizontalLayout_3.addWidget(self.button_new_account)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign in"))
        self.label_login.setText(_translate("MainWindow", "Login"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.button_sign_in.setText(_translate("MainWindow", "Sign in"))
        self.button_new_account.setText(_translate("MainWindow", "Create account"))

    def try_sign_in(self):
        if self.entry_login.text() and self.entry_password.text():
            try:
                user = sign_in(self.entry_login.text(), self.entry_password.text())
                print(user.get_login(), user.get_password())
            except LoginException as e:
                self.statusBar.showMessage(str(e), 1500)
        else:
            self.statusBar.showMessage("Login or password not provided", 1500)

    def try_register(self):
        if self.entry_login.text() and self.entry_password.text():
            try:
                user = register(self.entry_login.text(), self.entry_password.text())
                save_pickled(user)
                print(user.get_login(), user.get_password())
            except LoginException as e:
                self.statusBar.showMessage(str(e), 1500)
        else:
            self.statusBar.showMessage("Login or password not provided", 1500)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
