# Created by: PyQt5 UI code generator 5.15.4

from PyQt5 import QtCore, QtGui, QtWidgets
import py.filters as fil
from py.constants import *
import urllib.request
from py.User import save_pickled, User


class MainApp(QtWidgets.QMainWindow):
    def __init__(self, parent):
        super(MainApp, self).__init__(parent)
        self.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        self.setupUi()

    def setupUi(self):
        self.setEnabled(True)
        self.resize(1510, 861)
        self.setMouseTracking(False)
        self.setStyleSheet("")
        self.icon_not_fav = QtGui.QIcon()
        self.icon_not_fav.addPixmap(QtGui.QPixmap("icons/not_fav.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_fav = QtGui.QIcon()
        self.icon_fav.addPixmap(QtGui.QPixmap("icons/is_fav.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.centralwidget = QtWidgets.QWidget(self)
        self.cocktail_list = QtWidgets.QScrollArea(self.centralwidget)
        self.cocktail_list.setGeometry(QtCore.QRect(10, 110, 581, 741))
        self.cocktail_list.setWidgetResizable(True)
        self.cocktails_list = QtWidgets.QWidget()
        self.cocktails_list.setGeometry(QtCore.QRect(0, 0, 579, 739))
        self.cocktail_list.setWidget(self.cocktails_list)
        self.cocktail_details = QtWidgets.QFrame(self.centralwidget)
        self.cocktail_details.setGeometry(QtCore.QRect(600, 10, 851, 841))
        self.cocktail_details.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cocktail_details.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cocktail_image = QtWidgets.QLabel(self.cocktail_details)
        self.cocktail_image.setGeometry(QtCore.QRect(10, 10, 200, 200))
        self.cocktail_image.setAutoFillBackground(False)
        self.cocktail_image.setText("")
        self.ingredient_list = QtWidgets.QListView(self.cocktail_details)
        self.ingredient_list.setGeometry(QtCore.QRect(0, 230, 851, 451))
        self.ingredient_list.setInputMethodHints(QtCore.Qt.ImhNone)
        self.cocktail_name = QtWidgets.QLabel(self.cocktail_details)
        self.cocktail_name.setGeometry(QtCore.QRect(230, 10, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cocktail_name.setFont(font)
        self.cocktail_id = QtWidgets.QLabel(self.cocktail_details)
        self.cocktail_id.setGeometry(QtCore.QRect(230, 50, 481, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(True)
        self.cocktail_id.setFont(font)
        self.glass_label = QtWidgets.QLabel(self.cocktail_details)
        self.glass_label.setGeometry(QtCore.QRect(230, 130, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.glass_label.setFont(font)
        self.category_label = QtWidgets.QLabel(self.cocktail_details)
        self.category_label.setGeometry(QtCore.QRect(230, 160, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.category_label.setFont(font)
        self.alcoholic_label = QtWidgets.QLabel(self.cocktail_details)
        self.alcoholic_label.setGeometry(QtCore.QRect(230, 190, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.alcoholic_label.setFont(font)
        self.alcoholic_label.setAutoFillBackground(False)
        self.cocktail_category = QtWidgets.QLabel(self.cocktail_details)
        self.cocktail_category.setGeometry(QtCore.QRect(320, 160, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.cocktail_category.setFont(font)
        self.cocktail_glass = QtWidgets.QLabel(self.cocktail_details)
        self.cocktail_glass.setGeometry(QtCore.QRect(290, 130, 551, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.cocktail_glass.setFont(font)
        self.cocktail_alcoholic = QtWidgets.QLabel(self.cocktail_details)
        self.cocktail_alcoholic.setGeometry(QtCore.QRect(320, 190, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.cocktail_alcoholic.setFont(font)
        self.cocktail_decription = QtWidgets.QLabel(self.cocktail_details)
        self.cocktail_decription.setGeometry(QtCore.QRect(20, 720, 811, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.cocktail_decription.setFont(font)
        self.cocktail_decription.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cocktail_decription.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cocktail_decription.setInputMethodHints(QtCore.Qt.ImhNone)
        self.cocktail_decription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cocktail_decription.setWordWrap(True)
        self.description_label = QtWidgets.QLabel(self.cocktail_details)
        self.description_label.setGeometry(QtCore.QRect(10, 690, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.description_label.setFont(font)
        self.description_label.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.ingr_measure_1 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_1.setGeometry(QtCore.QRect(120, 300, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_1.setFont(font)
        self.ingr_measure_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_1 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_1.setGeometry(QtCore.QRect(120, 250, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_1.setFont(font)
        self.ingr_name_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_1.setWordWrap(True)
        self.ingr_image_1 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_1.setGeometry(QtCore.QRect(10, 240, 100, 100))
        self.ingr_image_1.setText("")
        self.ingr_measure_2 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_2.setGeometry(QtCore.QRect(400, 300, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_2.setFont(font)
        self.ingr_measure_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_2 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_2.setGeometry(QtCore.QRect(400, 250, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_2.setFont(font)
        self.ingr_name_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_2.setWordWrap(True)
        self.ingr_image_2 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_2.setGeometry(QtCore.QRect(290, 240, 100, 100))
        self.ingr_image_2.setText("")
        self.ingr_measure_3 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_3.setGeometry(QtCore.QRect(680, 300, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_3.setFont(font)
        self.ingr_measure_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_3 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_3.setGeometry(QtCore.QRect(680, 250, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_3.setFont(font)
        self.ingr_name_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_3.setWordWrap(True)
        self.ingr_image_3 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_3.setGeometry(QtCore.QRect(570, 240, 100, 100))
        self.ingr_image_3.setText("")
        self.ingr_measure_4 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_4.setGeometry(QtCore.QRect(120, 410, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_4.setFont(font)
        self.ingr_measure_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_4 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_4.setGeometry(QtCore.QRect(120, 360, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_4.setFont(font)
        self.ingr_name_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_4.setWordWrap(True)
        self.ingr_image_4 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_4.setGeometry(QtCore.QRect(10, 350, 100, 100))
        self.ingr_image_4.setText("")
        self.ingr_measure_5 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_5.setGeometry(QtCore.QRect(400, 410, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_5.setFont(font)
        self.ingr_measure_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_5 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_5.setGeometry(QtCore.QRect(400, 360, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_5.setFont(font)
        self.ingr_name_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_5.setWordWrap(True)
        self.ingr_image_5 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_5.setGeometry(QtCore.QRect(290, 350, 100, 100))
        self.ingr_image_5.setText("")
        self.ingr_measure_6 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_6.setGeometry(QtCore.QRect(680, 410, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_6.setFont(font)
        self.ingr_measure_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_6 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_6.setGeometry(QtCore.QRect(680, 360, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_6.setFont(font)
        self.ingr_name_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_6.setWordWrap(True)
        self.ingr_image_6 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_6.setGeometry(QtCore.QRect(570, 350, 100, 100))
        self.ingr_image_6.setText("")
        self.ingr_measure_7 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_7.setGeometry(QtCore.QRect(120, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_7.setFont(font)
        self.ingr_measure_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_7 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_7.setGeometry(QtCore.QRect(120, 470, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_7.setFont(font)
        self.ingr_name_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_7.setWordWrap(True)
        self.ingr_image_7 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_7.setGeometry(QtCore.QRect(10, 460, 100, 100))
        self.ingr_image_7.setText("")
        self.ingr_measure_8 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_8.setGeometry(QtCore.QRect(400, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_8.setFont(font)
        self.ingr_measure_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_8 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_8.setGeometry(QtCore.QRect(400, 470, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_8.setFont(font)
        self.ingr_name_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_8.setWordWrap(True)
        self.ingr_image_8 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_8.setGeometry(QtCore.QRect(290, 460, 100, 100))
        self.ingr_image_8.setText("")
        self.ingr_measure_9 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_9.setGeometry(QtCore.QRect(680, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_9.setFont(font)
        self.ingr_measure_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_9 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_9.setGeometry(QtCore.QRect(680, 470, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_9.setFont(font)
        self.ingr_name_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_9.setWordWrap(True)
        self.ingr_image_9 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_9.setGeometry(QtCore.QRect(570, 460, 100, 100))
        self.ingr_image_9.setText("")
        self.ingr_measure_10 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_10.setGeometry(QtCore.QRect(120, 630, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_10.setFont(font)
        self.ingr_measure_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_10 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_10.setGeometry(QtCore.QRect(120, 580, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_10.setFont(font)
        self.ingr_name_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_10.setWordWrap(True)
        self.ingr_image_10 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_10.setGeometry(QtCore.QRect(10, 570, 100, 100))
        self.ingr_image_10.setText("")
        self.ingr_measure_11 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_11.setGeometry(QtCore.QRect(400, 630, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_11.setFont(font)
        self.ingr_measure_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_11 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_11.setGeometry(QtCore.QRect(400, 580, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_11.setFont(font)
        self.ingr_name_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_11.setWordWrap(True)
        self.ingr_image_11 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_11.setGeometry(QtCore.QRect(290, 570, 100, 100))
        self.ingr_image_11.setText("")
        self.ingr_measure_12 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_measure_12.setGeometry(QtCore.QRect(680, 630, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.ingr_measure_12.setFont(font)
        self.ingr_measure_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_12 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_name_12.setGeometry(QtCore.QRect(680, 580, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ingr_name_12.setFont(font)
        self.ingr_name_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingr_name_12.setWordWrap(True)
        self.ingr_image_12 = QtWidgets.QLabel(self.cocktail_details)
        self.ingr_image_12.setGeometry(QtCore.QRect(570, 570, 100, 100))
        self.ingr_image_12.setText("")
        self.add_to_fav_button = QtWidgets.QPushButton(self.cocktail_details)
        self.add_to_fav_button.setGeometry(QtCore.QRect(730, 10, 111, 111))
        self.add_to_fav_button.setText("")
        self.add_to_fav_button.setIconSize(QtCore.QSize(80, 80))
        self.serach_label = QtWidgets.QLabel(self.centralwidget)
        self.serach_label.setGeometry(QtCore.QRect(10, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.serach_label.setFont(font)
        self.search_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_edit.setGeometry(QtCore.QRect(10, 50, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.search_edit.setFont(font)
        self.search_edit.setText("")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(540, 50, 41, 41))
        self.search_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/loupe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon1)
        self.search_button.setIconSize(QtCore.QSize(24, 24))
        self.choisees_list = QtWidgets.QComboBox(self.centralwidget)
        self.choisees_list.setGeometry(QtCore.QRect(390, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.choisees_list.setFont(font)
        self.choisees_list.addItem("")
        self.choisees_list.addItem("")
        self.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(self)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(40, 50))
        self.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.action_fav = QtWidgets.QAction(self)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/favorite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_fav.setIcon(icon2)
        self.action_logout = QtWidgets.QAction(self)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_logout.setIcon(icon3)
        self.action_home = QtWidgets.QAction(self)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_home.setIcon(icon4)
        self.action_random = QtWidgets.QAction(self)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/shuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_random.setIcon(icon5)
        self.action_ten_random = QtWidgets.QAction(self)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/ten.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ten_random.setIcon(icon6)
        self.action_non_alc = QtWidgets.QAction(self)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/non_alc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_non_alc.setIcon(icon7)
        self.action_opt_alc = QtWidgets.QAction(self)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/opt_alc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_opt_alc.setIcon(icon8)
        self.toolBar.addAction(self.action_home)
        self.toolBar.addAction(self.action_fav)
        self.toolBar.addAction(self.action_non_alc)
        self.toolBar.addAction(self.action_opt_alc)
        self.toolBar.addAction(self.action_random)
        self.toolBar.addAction(self.action_ten_random)
        self.toolBar.addAction(self.action_logout)

        self.retranslateUi()
        self.ingr_img = [self.ingr_image_1, self.ingr_image_2, self.ingr_image_3,
                         self.ingr_image_4, self.ingr_image_5, self.ingr_image_6,
                         self.ingr_image_7, self.ingr_image_8, self.ingr_image_9,
                         self.ingr_image_10, self.ingr_image_11, self.ingr_image_12]
        self.ingr_names = [self.ingr_name_1, self.ingr_name_2, self.ingr_name_3,
                           self.ingr_name_4, self.ingr_name_5, self.ingr_name_6,
                           self.ingr_name_7, self.ingr_name_8, self.ingr_name_9,
                           self.ingr_name_10, self.ingr_name_11, self.ingr_name_12]
        self.ingr_meas = [self.ingr_measure_1, self.ingr_measure_2, self.ingr_measure_3,
                          self.ingr_measure_4, self.ingr_measure_5, self.ingr_measure_6,
                          self.ingr_measure_7, self.ingr_measure_8, self.ingr_measure_9,
                          self.ingr_measure_10, self.ingr_measure_11, self.ingr_measure_12]

        self.action_home.triggered.connect(self.show_popular)
        self.action_non_alc.triggered.connect(self.show_non_alcoholic)
        self.action_opt_alc.triggered.connect(self.show_opt_alcoholic)
        self.action_ten_random.triggered.connect(self.show_ten_random)
        self.action_random.triggered.connect(self.show_random)
        self.action_logout.triggered.connect(self.logout)
        self.action_fav.triggered.connect(self.show_favourite)
        self.search_button.clicked.connect(self.show_searched)
        self.add_to_fav_button.clicked.connect(self.add_to_fav)
        self.show_popular()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.glass_label.setText(_translate("self", "Glass: "))
        self.category_label.setText(_translate("self", "Category: "))
        self.alcoholic_label.setText(_translate("self", "Alcoholic: "))
        self.description_label.setText(_translate("self", "Description: "))
        self.add_to_fav_button.setShortcut(_translate("self", "Ctrl+A"))
        self.serach_label.setText(_translate("self", "Search"))
        self.search_button.setShortcut(_translate("self", "Return"))
        self.choisees_list.setItemText(0, _translate("self", "Name"))
        self.choisees_list.setItemText(1, _translate("self", "Ingredients"))
        self.toolBar.setWindowTitle(_translate("self", "toolBar"))
        self.action_fav.setText(_translate("self", "fav"))
        self.action_fav.setShortcut(_translate("self", "Ctrl+F"))
        self.action_logout.setText(_translate("self", "logout"))
        self.action_logout.setShortcut(_translate("self", "Ctrl+X"))
        self.action_home.setText(_translate("self", "home"))
        self.action_home.setShortcut(_translate("self", "Ctrl+H"))
        self.action_random.setText(_translate("self", "random"))
        self.action_random.setShortcut(_translate("self", "Ctrl+R"))
        self.action_ten_random.setText(_translate("self", "ten_random"))
        self.action_ten_random.setShortcut(_translate("self", "Ctrl+T"))
        self.action_non_alc.setText(_translate("self", "non_alc"))
        self.action_non_alc.setShortcut(_translate("self", "Ctrl+B"))
        self.action_opt_alc.setText(_translate("self", "opt_alc"))
        self.action_opt_alc.setShortcut(_translate("self", "Ctrl+G"))

    def show_cocktail_details(self, id):
        cocktail = fil.lookup_cocktail_by_id(id)
        cocktail = cocktail[0]

        url = str(cocktail['strDrinkThumb'] + '/preview')
        data = urllib.request.urlopen(url).read()
        image = QtGui.QImage()
        image.loadFromData(data)
        pixmap = QtGui.QPixmap.fromImage(image)

        self.cocktail_image.setPixmap(pixmap)
        self.cocktail_name.setText(cocktail['strDrink'])
        self.cocktail_id.setText(cocktail['idDrink'])
        self.cocktail_alcoholic.setText(cocktail['strAlcoholic'])
        self.cocktail_category.setText(cocktail['strCategory'])
        self.cocktail_glass.setText(cocktail['strGlass'])

        for i in range(0, 12):
            if not cocktail['strIngredient' + str(i + 1)]:
                break
            url = str(image_of_ingredient + cocktail['strIngredient' + str(i + 1)] + "-Small.png")
            data = urllib.request.urlopen(url).read()
            image = QtGui.QImage()
            image.loadFromData(data)
            pixmap = QtGui.QPixmap.fromImage(image)

            self.ingr_img[i].setPixmap(pixmap)
            self.ingr_names[i].setText(cocktail['strIngredient' + str(i + 1)])
            self.ingr_meas[i].setText(cocktail['strMeasure' + str(i + 1)])

        self.cocktail_decription.setText(cocktail['strInstructions'])
        if any(self.cocktail_id.text() == fav['idDrink'] for fav in User.currentUser.get_favourite()):
            self.add_to_fav_button.setIcon(self.icon_fav)
        else:
            self.add_to_fav_button.setIcon(self.icon_not_fav)

    def prepare_and_show_list(self, cocktails):
        group_list = QtWidgets.QGroupBox()
        layout = QtWidgets.QFormLayout()

        if cocktails and cocktails != "None Found":
            font = QtGui.QFont()
            font.setFamily("Arial")
            font.setPointSize(18)
            font.setBold(True)
            for dict in cocktails:
                url = str(dict['strDrinkThumb'] + '/preview')
                data = urllib.request.urlopen(url).read()
                image = QtGui.QImage()
                image.loadFromData(data)
                pixmap = QtGui.QPixmap.fromImage(image)
                icon = QtGui.QIcon(pixmap)

                button = QtWidgets.QPushButton(str(" " + dict['strDrink']))
                button.setIcon(icon)
                button.setIconSize(QtCore.QSize(80, 80))
                button.setFixedHeight(100)
                button.setFont(font)
                button.setStyleSheet("text-align: left")
                button.clicked.connect(lambda state, id=dict['idDrink']: self.show_cocktail_details(id))

                layout.addRow(button)

            self.show_cocktail_details(cocktails[0]['idDrink'])

        group_list.setLayout(layout)
        self.cocktail_list.setWidget(group_list)

    def show_searched(self):
        if not self.search_edit.text():
            cocktails = None
        else:
            if self.choisees_list.currentText().__eq__("Ingredients"):
                cocktails = fil.get_filter_by_ingredients(self.search_edit.text())
            else:
                cocktails = fil.get_cocktails_by_name(self.search_edit.text())
        self.prepare_and_show_list(cocktails)

    def show_popular(self):
        cocktails = fil.lookup_popular()
        self.prepare_and_show_list(cocktails)

    def show_favourite(self):
        cocktails = User.currentUser.get_favourite()
        self.prepare_and_show_list(cocktails)

    def show_non_alcoholic(self):
        cocktails = fil.get_filter_by_alcoholic("Non Alcoholic")
        self.prepare_and_show_list(cocktails)

    def show_opt_alcoholic(self):
        coctails = fil.get_filter_by_alcoholic("Optional alcohol")
        self.prepare_and_show_list(coctails)

    def show_ten_random(self):
        cocktails = fil.lookup_ten_random()
        self.prepare_and_show_list(cocktails)

    def show_random(self):
        cocktails = fil.lookup_random()
        self.prepare_and_show_list(cocktails)

    def add_to_fav(self):
        favourite = User.currentUser.get_favourite()

        if any(self.cocktail_id.text() == fav['idDrink'] for fav in favourite):
            User.currentUser.remove_favourite(fil.lookup_cocktail_by_id(self.cocktail_id.text())[0])
            self.add_to_fav_button.setIcon(self.icon_not_fav)
        else:
            User.currentUser.add_favourite_drink(fil.lookup_cocktail_by_id(self.cocktail_id.text())[0])
            self.add_to_fav_button.setIcon(self.icon_fav)

    def logout(self):
        self.search_edit.setText("")
        self.hide()
        self.parent().show()
        save_pickled()

    def closeEvent(self, event):
        save_pickled()
